name: Upload to S3
description: Upload a file to an S3 bucket

inputs:
  source:
    description: 'The source file path to upload'
    required: true
  destination:
    description: 'The target path (key) in the S3 bucket'
    required: true
  bucket:
    description: 'The name of the S3 bucket'
    required: true
  region:
    description: 'The AWS region where the bucket resides'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload file to S3
      shell: bash
      run: |
        echo "Uploading ${{ inputs.source }} to s3://${{ inputs.bucket }}/${{ inputs.destination }}"
        aws s3 cp "${{ inputs.source }}" "s3://${{ inputs.bucket }}/${{ inputs.destination }}" \
          --region "${{ inputs.region }}"
