name: Upload to S3
description: Upload files or folders to an S3 bucket.
inputs:
  source:
    description: 'File or folder path to upload'
    required: true
  destination:
    description: 'S3 key or prefix to upload to'
    required: true
  bucket:
    description: 'S3 bucket name'
    required: true
  region:
    description: 'AWS region'
    required: true
runs:
  using: 'node20'
  main: 'upload.js'
