name: Deploy to AWS S3 + CloudFront + CloudFront Invalidation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Capture start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare meta files
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          mkdir -p public/meta
          cp README.md public/meta/${REPO_NAME}.md
          cp package.json public/meta/
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Upload README to S3
        uses: ramaeondev/therama.dev/.github/actions/upload-to-s3@master
        with:
          source: public/meta/${{ env.REPO_NAME }}.md
          destination: readme/${{ env.REPO_NAME }}.md
          bucket: ${{ secrets.S3_UPLOAD_BUCKET }}
          region: ${{ secrets.AWS_UPLOAD_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GLOBAL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GLOBAL }}

      - name: Log deployment to Supabase
        uses: ./.github/actions/log-and-update-deployment
        with:
          start_time: ${{ env.START_TIME }}
          job_status: ${{ job.status }}
